version: '3.8'  # Используется версия Docker Compose 3.8

services:
  nginx:
    image: nginx:latest
    ports:
      - "90:8000"
    volumes:
      - /root/nginx/nginx-config:/ect/nginx
      - /root/nginx/nginx.conf:/etc/nginx/nginx.conf
    restart: unless-stopped
